### PR TITLE
fix: tabs are broken

### LINKED ISSUE #1037: add a new data table or analysis are broken

### PR DESCRIPTION
**Pull request by MAudelGisaia**
- close #1037

### CODE REVIEW

**Review by QuCMGisaia — APPROVED** [review]

**Review by sebbousquet — APPROVED** [review]

File: src/app/modules/result-list-config/components/global-result-list/global-result-list.component.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@
 
 import { EditTabComponent } from '@analytics-config/components/edit-tab/edit-tab.component';
 import { ResultlistConfigForm } from '@analytics-config/services/resultlist-form-builder/resultlist-form-builder.service';
-import { Component, OnDestroy } from '@angular/core';
+import { Component, OnDestroy, signal, ViewChild } from '@angular/core';
```
Comment (MohamedHamouGisaia) [inline src/app/modules/result-list-config/components/global-result-list/global-result-list.component.ts:22]: signal doesn't seem to be used, should it be removed ?

**Review by MohamedHamouGisaia — APPROVED** [review]
